site_name: Labforge docs
site_url: ""
copyright: "2025, Ilya Zamaratskikh"
site_author: "Ilya Zamaratskikh"

repo_url: https://gitverse.ru/mrtstg/labforge-oss

extra:
  social:
    - icon: fontawesome/brands/gitlab
      name: Gitverse mirror
      link: https://gitverse.ru/mrtstg/labforge-oss

theme:
  icon:
    repo: fontawesome/brands/git
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
  name: material
  language: ru
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Введение: ./index.md
  - Руководство разработки:
    - Общее описание системы: dev-guide/index.md
    - Конфигурация сервисов: dev-guide/configuration.md
    - Реализация VNC-подключения к ВМ: dev-guide/remote.md
  - Руководство пользователя: 
    - Вход и работа со стендами: user-guide/index.md
    - Добавление образов VM: usage-guide/image-management.md
    - Создание шаблонов развертывания: usage-guide/deployment-templates.md
    - Система мониторинга: usage-guide/monitoring.md
    - Решение проблем при ошибках развертывания: usage-guide/deployment-errors.md
  - Руководство установки:
    - Требования к окружению: install-guide/requirements.md
    - Установка из установщика: install-guide/installer.md
    - Пост-установочные шаги: install-guide/postinstall.md
  - Работа с Keycloak:
    - Вход в Realm: keycloak/entering-realm.md
    - Создание локальных пользователей: keycloak/local-users.md
    - Присвоение ролей пользователям: keycloak/users-role.md
    - Создание групп пользователей: keycloak/creating-groups.md
  - proxmox-compose:
    - Основы использования: proxmox-compose/index.md
  - Known issues: known-issues.md

draft_docs: |
  install-guide/repository.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

plugins: 
  - search:
      lang: [en, ru]
