build: ../frontend-server/static
	mkdir -p ../frontend-server/static/css
	mkdir -p ../frontend-server/static/js
	yarn build
	mv dist/index.js ../frontend-server/static/js/vnc.js
	mv dist/index.css ../frontend-server/static/css/vnc.css
