resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/15.yaml

packages:
- .
- ../proxmox-api/
- ../../proxmox-fs-agent/proxmox-fs-agent-api/

extra-deps: []
