FROM mrtstg/kpfu-debian:bullseye AS builder
RUN apt-get update
RUN apt-get install zlib1g-dev libpq-dev make curl build-essential curl libffi-dev libgmp-dev libgmp10 libncurses-dev libncurses6 libtinfo6 pkg-config -y
RUN curl https://downloads.haskell.org/~ghcup/x86_64-linux-ghcup > /usr/bin/ghcup && chmod +x /usr/bin/ghcup
RUN ghcup -v install ghc 9.4.7
RUN ghcup -v install cabal latest
RUN ghcup -v install stack latest
ENV PATH=${PATH}:/root/.local/bin
ENV PATH=${PATH}:/root/.ghcup/bin
COPY deployment/stack.yaml /root/.stack/config.yaml
RUN stack update
WORKDIR /ln2
COPY libraries ./libraries/
COPY proxmox-fs-agent ./proxmox-fs-agent
