{
 "title": "NGINX",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": {
     "query": "label_values(nginx_up,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Handled connections delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "changes(nginx_connections_handled{instance=\"$Instance\"}[$__interval])",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Successful metric requests percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A * 100", "type": "math" }
   ]
  },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "nginx_connections_active{instance=\"$Instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}