name:                redis-utils
version:             0.1.0.0
github:              "learnew2/redis-utils"
license:             BSD-3-Clause
author:              "Ilya Zamaratskikh"
maintainer:          "mrtstg@yandex.ru"
copyright:           "2024 Ilya Zamaratskikh"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/learnew2/redis-utils#readme>

dependencies:
- base >= 4.7 && < 5
- aeson == 2.1.2.1
- bytestring == 0.11.5.2
- hedis == 0.15.2
- mtl == 2.2.2
- text ^>= 2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
