snapshot:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/15.yaml

packages:
- .
- ../libraries/keycloak-api
- ../libraries/api-common
- ../libraries/proxmox-api
- ../libraries/proxmox-deploy-toolkit
- ../proxmox-fs-agent/proxmox-fs-agent-api
- ../libraries/redis-utils

extra-deps:
  - async-pool-0.9.2@sha256:532b356a3a2d3e6ec848ca266b566f8cf60c52a107f4b2c7e690cdd2b1ae67b2,1605
