snapshot:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/15.yaml

packages:
- .

extra-deps:
- git: https://github.com/learnew2/proxmox-fs-agent.git
  commit: 6f62d1b7f847c0d9d36516d3bb18dd4991693cd9
  subdirs:
    - proxmox-fs-agent-api
- /home/ilya/projects/other/learnew2/proxmox-api
- /home/ilya/projects/other/learnew2/proxmox-deploy-toolkit
